name: CI Checks

on: [pull_request]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: "ubuntu-20.04"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rcareworld
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd pyrcareworld
          pip install -r requirements.txt
          pip install -e .
          pip uninstall -y numpy
          conda install numpy
          cd ../

      - name: Run unit tests
        run: |
          pytest tests/test_angle_functions.py
          pytest tests/test_dressing_env.py
          pytest -s tests/test_bathing_env.py
          pytest tests/test_save_scene.py
          
